version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: microplazoleta-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microplazoleta
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
